### ISSUE TITLE
	PANTHER:PTN001146520 tea1 NOT cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2117] opened 2018-10-13 18:54 UTC
tea1 isn't involved in cytokinesis

tea1 | cell end marker Tea1 |   | mitotic actomyosin contractile ring localization |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001146520PomBase:SPAC6G10.02c | kelch repeat domain pthr23244 | protein |   | PMID:21873635 | 20171207

**Comment by pgaudet** [comment] 2018-11-12 09:23
Duplicate of #2167
I dont see 'mitotic actomyosin contractile ring localization' being propagated in PAINT. 

According to a file @dustine32 sent me, the last modification to that family was done on 2017-12-07. 

I don't understand why this looks different @dustine32 - any idea? 

Thanks, Pascale

**Comment by dustine32** [comment] 2018-11-13 16:44
I think this issue got cleared out recently due to whatever change, possibly related to PAINT GAF generation (e.g. https://github.com/geneontology/go-annotation/issues/2104#issuecomment-436723354 for IKR/IRDs to leaf nodes). Looking for `SPCC1223.06` annotated to `GO:1902405` I don't see it in the latest file:
```
$ curl -L ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_pombase.gaf.gz | gunzip | grep SPCC1223.06
PomBase	SPCC1223.06	tea1		GO:0051285	PMID:21873635	IBA	PANTHER:PTN001146520|PomBase:SPAC6G10.02c	C	Tip elongation aberrant protein 1	UniProtKB:P87061|PTN000582306	protein	taxon:284812	20171207	GO_Central
PomBase	SPCC1223.06	tea1		GO:0008360	PMID:21873635	IBA	PANTHER:PTN001906771|SGD:S000001201|UniProtKB:G5EAY1	P	Tip elongation aberrant protein 1	UniProtKB:P87061|PTN000582306	protein	taxon:284812	20171207	GO_Central
```

**Comment by pgaudet** [comment] 2018-11-13 16:46
This matches what I see in PAINT and in Pantree. 

How can we tell where this is coming from ?

**Comment by ValWood** [comment] 2018-11-13 17:36
This is coming from the function process inference file.
i.e. source GO_central.
When was this updated?

**Comment by dustine32** [comment] 2018-11-13 18:53
Oh now I see this wasn't due to the GAF generation script change. The IBD of `PTN001146520` to `GO:1902405` was simply obsoleted by Marc Feuermann on 11/5/18.

**Comment by pgaudet** [comment] 2018-11-14 08:45
OK good, thanks for checking @dustine32  

@ValWood We should always wait for a new release before re-opening tickets. Now there hasn't been an AmiGO release since Oct 9th, this is why I haven't looked at the tickets you opened - some may have been closed but we can't seen. 

Thanks, Pascale

**Comment by ValWood** [comment] 2018-11-14 09:45
I'm trying not to duplicate but it's difficult to know how long changes will take. I would expect May changes to be through by now?

**Comment by pgaudet** [comment] 2018-11-14 09:51
I think 11/5/18 is November, not May ? 

I can't find the ticket :( 
Neither with tea1 or PTN001146520 or SPCC1223.06	or pthr23244

Weird !!!! 

Maybe it's another PTN of pthr23244 that also fixed this one ?

**Comment by mah11** [comment] 2018-11-19 12:03
> I think 11/5/18 is November, not May ?

this is why ISO date format is your friend

**Comment by pgaudet** [comment] 2018-11-19 15:55
OK, gone in the release from Friday. 

:)

**Closed by pgaudet** 2018-11-19 15:55 UTC
Labels: PAINT annotation
