### ISSUE TITLE
PANTHER:PTN000548991  (PTHR23044) (eri1) DNA catabolic process/ ribosome biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2746] opened 2020-01-09 16:37 UTC
WB:WBGene00000797  does not appear to be the ortholog  of pombe eri1.

eri1 | double-strand siRNA ribonuclease Eri1 |   | DNA catabolic process, exonucleolytic |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000548991WB:WBGene00000797 | 3'-5' exonuclease eri1-related pthr23044 | protein |   | PMID:21873635 | 20170228

WBGene00001332 | eri-1
is the worm ortholog

**Comment by pgaudet** [comment] 2020-01-09 21:11
What annotation are you disputing ? This family has many duplications, but the MF exonuclease activity' seems OK for all the genes.

**Comment by ValWood** [comment] 2020-01-11 14:55
DNA catabolic process, exonucleolytic 
and anything apoptotic.

All of these annotations seem to come from worm. I  wonder if these are correct. this is definitely RNAi pathway (it is also absent from S. cerevisiae which is the normal taxonomic conservation pattern for  RNAi.
I wonder if the DNA metabolism and apoptosis are functionally relevant in worm

**Comment by ValWood** [comment] 2020-01-11 15:03
It's odd becasue in wormbase the papers are all quite old, and don't really focus on RNAi. Bu t the human annotation says
 enhanced RNAi three prime mRNA exonuclease homolog 1 (C.elegans) 
although in wormbase eri1 is called crn-4

**Comment by ValWood** [comment] 2020-01-11 15:05
Hang on there are 2 worm proteins with inferences
WB:WBGene00001332  and WB:WBGene00000797

This is the ortholog of WB:WBGene00001332 (eri1)

**Comment by ValWood** [comment] 2020-01-11 15:08
see

PMID:18438419

The exonuclease ERI-1 has a conserved dual role in 5.8S rRNA processing and RNAi.

The exonuclease ERI-1 negatively regulates RNA interference in Caenorhabditis elegans and Schizosaccharomyces pombe, and is required for production of some C. elegans endogenous small interfering RNAs. We show that ERI-1 performs 3' end processing of the 5.8S ribosomal RNA in both C. elegans and S. pombe. In C. elegans, two protein isoforms of ERI-1 are localized to the cytoplasm, and each has distinct functions in ribosomal RNA processing and negative regulation of RNA interference.

**Comment by ValWood** [comment] 2021-04-07 10:36
This seems to be a family issue.
WB:WBGene00000797 does not appear to be the ortholog of pombe eri1.

**Comment by pgaudet** [comment] 2021-04-19 12:30
Duplicate of #3329

**Closed by pgaudet** 2021-04-19 12:30 UTC
Labels: Matrix, PAINT annotation, high priority
