### ISSUE TITLE
Proposal for Protein complexes representation in Noctua 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#1663] opened 2017-10-18 19:16 UTC
_From @pgaudet on October 17, 2017 11:7_

At the Oct 2017  GOC meeting, we decided to form a working group to provide guidance for protein complex representation in Noctua: Formulate the issue; make a proposal 

_Copied from original issue: geneontology/noctua#517_

**Comment by bmeldal** [comment] 2017-10-19 08:06
duplicate of https://github.com/geneontology/go-annotation/issues/1661 ?

I guess we added tickets before we saw what each other did!

**Comment by vanaukenk** [comment] 2017-10-23 18:01
Yes, this is a duplicate of #1661 and since there is more information in that ticket, I am going to close this one.

**Closed by vanaukenk** 2017-10-23 18:01 UTC
Labels: question
