### ISSUE TITLE
Review annotations to GO:0004704 NF-kappaB-inducing kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4737] opened 2023-09-13 14:47 UTC
Dear all, 

The proposal has been made to obsolete GO:0004704 NF-kappaB-inducing kinase activity
see https://github.com/geneontology/go-ontology/issues/24418

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1A58HfRXV2G7hs-VOzOaxIDlcKm3yRtiue5zUinT0HXA/edit#gid=0

Impacted groups: 
UniProt 1 @Antonialock 
MGI 1  @LiNiMGI 

Thanks.

**Comment by LiNiMGI** [comment] 2023-09-13 15:11
thanks, the mouse annotation was made by uniprot @ValWood

**Comment by ValWood** [comment] 2023-09-13 15:17
OK, sorry I read the wrong field!
Both for you @Antonialock !

**Comment by pgaudet** [comment] 2023-09-14 09:25
Duplicate of https://github.com/geneontology/go-annotation/issues/4692

@ValWood you will also need to obsolete the child, so these annotations are need fixing

**Closed** 2023-09-14 09:26 UTC
Labels: annotation review
