### ISSUE TITLE
Review annotations to cGMP-mediated signalling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4958] opened 2024-01-29 14:17 UTC
Dear all, 

The proposal has been made to obsolete cGMP-mediated signalling, and its regulation children

**Comment by pgaudet** [comment] 2024-01-29 14:18
Missing ID, report not generated (!)

**Comment by suzialeksander** [comment] 2024-08-05 22:43
duplicate of https://github.com/geneontology/go-annotation/issues/4959

**Closed by suzialeksander** 2024-08-05 22:43 UTC
Labels: annotation review, reg_ann_to_list_of_terms, no clear request
