### ISSUE TITLE
mappings to various responses to ionizing radiation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3559] opened 2020-12-16 11:13 UTC
We have mappings to 6  double-strand break repair genes to  "response to various ionizing radiation, and x-ray"

I don't think these are useful a process annotation, I would only use them in extensions to the actual processes.  Ionising radiation can cause most types of DNA damage. 
 Spo this uses"response to" very loosely. Sometimes "response to " refers to a specific signalling pathway but here it is dependent on what type of damage is caused. So it isn't really a response to the radiation, it is a response to the lesion.

so, I am going to filter all of these:
<img width="1029" alt="Screenshot 2020-12-16 at 09 51 23" src="https://user-images.githubusercontent.com/7359272/102341433-be450680-3f8f-11eb-9464-5a772231ef8c.png">

**Comment by pgaudet** [comment] 2020-12-16 12:26
Next time can you copy the PTN or PTHR IDs ? Those are a pain to type....

**Comment by pgaudet** [comment] 2020-12-16 12:47
* PTN000288287 = PTHR12604 Locked by @marcfeuermann Dec 4
Duplicate of #2846 
* PTHR002003775 = PTHR28529 Fixed
* PTHR001415033 = PTHR22942

**Comment by pgaudet** [comment] 2020-12-16 12:51
I'm closing this, the family left to fix is covered in #2846

Thanks, Pascale

**Closed by pgaudet** 2020-12-16 12:51 UTC
Labels: PAINT annotation, PomBase
