### ISSUE TITLE
Review annotation using extension 'regulates_o_has_output'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2616] opened 2019-08-26 13:55 UTC
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'regulates_o_has_output' in extensions: https://docs.google.com/spreadsheets/d/1ZWMfx_bbHTndvfPSnB5t8-fxtTo6wfRuSMacBx9ZuHY/edit#gid=0

All annotations are by MGI. 

Thanks, Pascale

**Comment by ukemi** [comment] 2019-12-12 19:10
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by ukemi** [comment] 2019-12-12 19:10
duplicate of #2611

**Closed** 2020-05-10 17:56 UTC
Labels: annotation review
