### ISSUE TITLE
goa_ref should be default

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1282] opened 2015-05-01 15:30 UTC
The standard GOA files have a massively inflated number of genes. This is confusing to users, e.g. [This Ticket](http://jira.geneontology.org/browse/GO-820)

Note that this will also have really bad effects on enrichment analyses, as genes get counted twice etc.

goa produces a file called `goa_ref`, in which annotations are collapsed to the reference proteome member. This is clearly more aligned with what users require and what we should be producing, so we should change. the full goa (non-ref) should be the obscurely named file people have to be looking for to find.

HOWEVER...

The one wrinkle here is that the protein chosen to be the ref changes over the year, and thus gets out of sync with the yearly-updated QfO. The advantage of using the full goa file with the massively inflated number of genes is that you have a much higher chance of getting a match to a QfO protein, and thus to PANTHER. 

Options are:
- Produce a file for species like human that is mapped to stable identifiers for genes like NCBI Gene or ENSEMBL
- Switch to goa_ref as being the default (i.e. rename files) and find some solution for synchrony with QfO

Reported by: cmungall

Original Ticket: [geneontology/annotation-issues/1306](https://sourceforge.net/p/geneontology/annotation-issues/1306)

**Comment by cmungall** [comment] 2016-04-27 00:33
Closing this as it is subsumed by: https://github.com/geneontology/go-site/issues/185

**Comment by pgaudet** [comment] 2017-11-29 16:59
@cmungall Did you mean to close this ticket?

**Comment by pgaudet** [comment] 2017-11-29 17:02
Is this a duplicate of https://github.com/geneontology/go-annotation/issues/1113 ?

**Closed** 2024-02-06 01:42 UTC
Labels: GOA, GAF
