### ISSUE TITLE
Human DNA Polymerase Alpha is involved in DNA double strand break repair

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1761] opened 2018-01-15 13:01 UTC
The human DNA polymerase alpha (P09884) has several annotations that say it's NOT involved in different types of DNA repair.  There are 2 PMIDs supporting this:
PMID:1730053 for UV-excision repair
and 
PMID:1508673 for nucleotide excision repair.
However, there is also evidence that it IS involved in double-strand break repair:
PMID: 11470886
This would mean that the parent GO category "DNA synthesis involved in DNA repair" would subsequently no longer be a "NOT".  See https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P09884

I hope that this is a helpful suggestion.

**Comment by ValWood** [comment] 2018-01-17 17:12
@pgaudet  who should this one go to?

**Comment by pgaudet** [comment] 2018-01-17 18:33
@keslingmj  Next time can you please provide the name (or group) of the contributors of the annotations? 
This is UniProt so I am assigning @ggeorghiou

**Comment by keslingmj** [comment] 2018-01-17 19:25
Hello.

Thanks for letting me know. I would be happy to do this.  This is my first contribution to the site.  I used to work with Panther 1999-2004.

**Comment by ggeorghiou** [comment] 2018-01-18 10:25
Yes, it's one of ours (EBI specifically). So some questions regarding this: having both a NOT annotation and an annotation to the same GO term is still allowed right? (This is just for my general knowledge).

With regards to editting the annotations: The papers mentioned that the NOT annotations stem from are still valid. It's just PMID:11470886 states Pol alpha is involved in double strand break repair which it has an annotation for to GO:0006303 (double-strand break repair via nonhomologous end joining). So should I just create an annotation to GO:0000731 (DNA synthesis involved in DNA repair) to PMID:11470886? I don't think it's right to remove the NOT annotations outright since those papers state clearly the type of DNA repair that it is not involved in. I can edit the NOT annotations to a more suitable GO term for the specific type of repair they are not involved in (i.e. GO:1904161 (UV-damage excision repair) and GO:0006289 (nucleotide-excision repair)).

Would that be agreeable?

**Comment by pgaudet** [comment] 2018-01-18 11:23
> having both a NOT annotation and an annotation to the same GO term is still allowed right? (
Yes

>I don't think it's right to remove the NOT annotations outright since those papers state clearly the type of DNA repair that it is not involved in.
I think the problem is the NOT annotation to the parent 'DNA repair'. 
You can put NOT to any specific pathway but if the parent has a NOT then we have a logical problem. 

Thanks, Pascale

**Comment by ggeorghiou** [comment] 2018-01-18 13:09
And they're fixed. Closing this ticket.

**Closed by ggeorghiou** 2018-01-18 13:09 UTC
Labels: annotation review

**Comment by keslingmj** [comment] 2018-01-18 14:01
My 2 cents: I think that this is a good way to do it—move the NOT to the child categories.
