### ISSUE TITLE
PTN002514495

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3442] opened 2020-10-27 13:51 UTC
pombe ubc12 |   
is NEDD8 conjugating enzyme, not ubiquitin conjugating anzyme

IBA with Q9Y2X8 , MGI:109240 , MGI:107411 , PTN002514495 , MGI:2384911 , WBGene00006713 , mms2 , FBgn0264848 , MGI:1914049 , Q9Y385 , MGI:2388672 , MGI:104632 , ubc4 , Q8N2K1 , MGI:107412 , P62837 , FBgn0011217 , MGI:1917343 , P51965 , P61077 , ubc13 , Q16763 , Q96LR5 , ubc11 , O00762 , Q9NPD8 , A1L167 , FBgn0026316 , P68036 , P51668 , FBgn0000173 , P61085

**Comment by sjm41** [comment] 2020-11-02 16:18
I think this is a duplicate of #2572 from Aug 2019 - some discussion there, but as you've found, problems remain.

**Comment by marcfeuermann** [comment] 2020-12-09 15:15
PTHR24068 is a huge family (almost 3000 leaves). It has now been cleaned and neddylation has been distinguished from ubiquitination.

**Closed by marcfeuermann** 2020-12-09 15:15 UTC
Labels: PAINT annotation, PomBase
