### ISSUE TITLE
[Protein2GO] Notification of annotation dispute concerning protein P55899 (PTHR16675) (Dispute ID: 2893)

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-annotation#1331] opened 2015-11-10 20:41 UTC
Moved from GO helpdesk:
http://jira.geneontology.org/browse/GO-864

A dispute has been raised over a GO annotation coming from your group. The details are given below.

If you agree with the dispute, please amend or delete the annotation accordingly. If, however, you disagree or need to respond to the disputer, you may contact the disputing curator by replying to this email.

SOURCE	ENTITY TYPE	ENTITY ID	GO ID	EVIDENCE	ECO ID	REFERENCE	WITH	EXTENSION
REFG	protein	P55899	GO:0019882	IBA	ECO:0000318	GO_REF:0000033	PANTHER:PTN000422281	

Dispute ID: 2893
Nature of dispute: This dispute concerns the GO term used
Details:
Hi

FCGRT Binds to the Fc region of monomeric immunoglobulins gamma. This mediates the uptake of IgG from milk. Suggesting a possible role in transfer of immunoglobulin G from mother to fetus.
However it does not bind to an antigen see the discussion about this protein in PMID:9546397 where it is used to illustrate that although it has a structure similar to HLA-A (MHC class I) proteins the 'peptide binding groove' is closed.

Please remove these annotations and the annotations to orthologous proteins

Thanks

Ruth

Sent by Protein2GO on behalf of Ruth Caroline Lovering (r.lovering@ucl.ac.uk)

**Comment by tberardini** [comment] 2015-11-10 20:43
@RLovering

**Comment by pgaudet** [comment] 2016-08-16 12:26
Duplicate of https://github.com/geneontology/go-annotation/issues/1332

**Closed by pgaudet** 2016-08-16 12:26 UTC
