### ISSUE TITLE
Develop guidelines/rules for dealing with annotation redundancy

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2060] opened 2018-08-28 00:15 UTC
- [ ] Redundant annotations from pipeline predictions (F-> P or CC-> MF)

- [ ] Redundant annotations from PAINT

- [ ] Redundant annotations from IEAs

- [ ] Redundant experimental annotations from different curation groups 

- [ ] Redundant annotations to parent and child terms

**Comment by ValWood** [comment] 2019-05-25 18:19
- [ ] redundant non experimental annotation (ISS/NAS/TAS/IC)

**Comment by pgaudet** [comment] 2019-05-28 16:08
Duplicate of https://github.com/geneontology/go-site/issues/943

**Closed by pgaudet** 2019-05-28 16:08 UTC
Labels: QC
