### ISSUE TITLE
Review annotations to GO:0004704 NF-kappaB-inducing kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4736] opened 2023-09-13 14:21 UTC
Dear all, 

The proposal has been made to obsolete GO:0004704 NF-kappaB-inducing kinase activity
see  https://github.com/geneontology/go-ontology/issues/24418

Experimental annotations that need to be reviewed are here:https://docs.google.com/spreadsheets/d/1LhgdpBmlxQTxuX-XzrvEa5NMkJh5Oyp5Df7k_5LcLEc/edit#gid=0

Impacted groups: 
UniProt : 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
No mappings

Thanks.

**Comment by pgaudet** [comment] 2023-09-14 05:20
Duplicate of https://github.com/geneontology/go-annotation/issues/4692

**Closed by pgaudet** 2023-09-14 05:20 UTC
Labels: annotation review, direct_ann_to_list_of_terms
