### ISSUE TITLE
PTN000965782 elongator (transcription indirect) - PTHR12435

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3682] opened 2021-03-16 09:49 UTC
This is elongator. These seem to be out of date annotations from when elongator was thought to be involved in transcription?

GO:0006357 | regulation of transcription by RNA polymerase II | IBA with B9GAG9 , locus:2014804 , PTN000965782 , S000001593

**Comment by pgaudet** [comment] 2021-04-14 16:30
Duplicate of #3673 
This has been fixed.

**Closed by pgaudet** 2021-04-14 16:30 UTC
Labels: high priority
